services:
  db:
    image: postgres:18
    container_name: postgres_db
    env_file:
      - secrets/db.env
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"

  mongodb:
    image: arm64v8/mongo:4.4.18
    container_name: mongo_db
    platform: linux/arm64
    env_file:
      - secrets/mongo.env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: backend_app
    env_file:
      - secrets/db.env
      - secrets/mongo.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    volumes:
      - ./:/workspace
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongodb
    command: bash -c "uvicorn main:server_app --host 0.0.0.0 --port 8000 --reload"

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    container_name: scraper_app
    env_file:
      - secrets/db.env
      - secrets/mongo.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - SSH_USER=developer
    volumes:
      - ./:/workspace
      - ./ssh/authorized_keys:/authorized_keys:ro
    depends_on:
      - db
      - mongodb
    ports:
      - "0.0.0.0:33000:22"

volumes:
  pgdata:
  mongo_data:
