services:
  db:
    image: postgres:17
    container_name: postgres_db
    env_file:
      - secrets/db.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:8
    container_name: mongo_db
    env_file:
      - secrets/mongo.env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend_app
    env_file:
      - secrets/db.env
      - secrets/mongo.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - PYTHONPATH=/workspace
      # Uncomment to disable the background loop during development
      # - ENABLE_BACKGROUND_TASKS=false
    volumes:
      - ./:/workspace
    working_dir: /workspace/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongodb
    command: uvicorn main:server_app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: . 
      dockerfile: frontend/Dockerfile
    container_name: frontend_app
    working_dir: /workspace/frontend
    volumes:
      - ./frontend:/workspace/frontend
      - frontend_node_modules:/workspace/frontend/node_modules
    ports:
      - "5173:8080"
    depends_on:
      - app

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - secrets/pgadmin.env
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
  mongo_data:
  frontend_node_modules:
